#include <Arduino.h>

#ifndef REPEATER_ACTIVATORS_H_
#define REPEATER_ACTIVATORS_H_

#define ACTIVATORS_DEBUG_MODE true

#define ACTIVATORS_RADIO_1_PTT 0x80
#define ACTIVATORS_RADIO_1_FAN 0x81
#define ACTIVATORS_RADIO_1_FREQ_DOWN 0x82
#define ACTIVATORS_RADIO_1_FREQ_UP 0x83
#define ACTIVATORS_RADIO_2_PTT 0x84
#define ACTIVATORS_RADIO_2_FAN 0x85
#define ACTIVATORS_RADIO_2_FREQ_DOWN 0x86
#define ACTIVATORS_RADIO_2_FREQ_UP 0x87 


#endif